[package]
name = "py_rslc"
version = "0.3.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"

[lib]
name = "rslc"
crate-type = ["cdylib"]

[dependencies]
rslc = { path = ".." }
numpy = "0.11.0"
pyo3 = { version = "0.11.1", features = ["extension-module"] }
paste = "1.0"
